In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

sns.set()  # устанавливаем seaborn по умолчанию для отрисовки графиков

In [39]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [40]:
df = pd.read_excel("drive/MyDrive/data/product/ABBREV_with_CLASS.xlsx")
df

,Unnamed: 0,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),...,FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_Desc1,GmWt_2,GmWt_Desc2,Refuse_Pct,CLASS
0,0,1001,"BUTTER,WITH SALT",15.87,717,0.85,81.11,2.11,0.06,0.0,...,51.368,21.021,3.043,215.0,5.00,"1 pat, (1"" sq, 1/3"" high)",14.2,1 tbsp,0.0,10
1,1,1002,"BUTTER,WHIPPED,W/ SALT",16.72,718,0.49,78.30,1.62,2.87,0.0,...,45.390,19.874,3.331,225.0,3.80,"1 pat, (1"" sq, 1/3"" high)",9.4,1 tbsp,0.0,10
2,2,1003,"BUTTER OIL,ANHYDROUS",0.24,876,0.28,99.48,0.00,0.00,0.0,...,61.924,28.732,3.694,256.0,12.80,1 tbsp,205.0,1 cup,0.0,0
3,3,1004,"CHEESE,BLUE",42.41,353,21.40,28.74,5.11,2.34,0.0,...,18.669,7.778,0.800,75.0,28.35,1 oz,17.0,1 cubic inch,0.0,10
4,4,1005,"CHEESE,BRICK",41.11,371,23.24,29.68,3.18,2.79,0.0,...,18.764,8.598,0.784,94.0,132.00,"1 cup, diced",113.0,"1 cup, shredded",0.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8785,8785,83110,"MACKEREL,SALTED",43.00,305,18.50,25.10,13.40,0.00,0.0,...,7.148,8.320,6.210,95.0,80.00,"1 piece, (5-1/2"" x 1-1/2"" x 1/2"")",17.0,"1 cubic inch, boneless",0.0,0
8786,8786,90240,"SCALLOP,(BAY&SEA),CKD,STMD",70.25,111,20.54,0.84,2.97,5.41,0.0,...,0.218,0.082,0.222,41.0,85.00,3 oz,NaN,NaN,0.0,0
8787,8787,90480,"SYRUP,CANE",26.00,269,0.00,0.00,0.86,73.14,0.0,...,0.000,0.000,0.000,0.0,21.00,1 serving,NaN,NaN,0.0,10
8788,8788,90560,"SNAIL,RAW",79.20,90,16.10,1.40,1.30,2.00,0.0,...,0.361,0.259,0.252,50.0,85.00,3 oz,NaN,NaN,0.0,0
8789,8789,93600,"TURTLE,GREEN,RAW",78.50,89,19.80,0.50,1.20,0.00,0.0,...,0.127,0.088,0.170,50.0,85.00,3 oz,NaN,NaN,0.0,0

In [41]:
df.drop(columns=['Unnamed: 0', 'GmWt_Desc1', 'GmWt_Desc2'], inplace=True)

In [42]:
df.describe()

,NDB_No,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),Calcium_(mg),...,Vit_D_IU,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_2,Refuse_Pct,CLASS
count,8790.000000,8789.000000,8790.000000,8790.000000,8790.000000,8465.000000,8790.000000,8196.000000,6958.000000,8442.000000,...,5579.000000,5227.000000,8441.000000,8124.000000,8125.000000,8380.000000,8490.000000,4825.000000,8740.000000,8790.000000
mean,15663.495222,54.112218,226.317634,11.342849,10.553725,1.783468,22.127710,2.187445,8.543066,76.738214,...,22.990142,15.631586,3.576334,4.081006,2.288767,40.613246,96.395130,250.747668,4.964416,5.715586
std,9251.413586,30.772854,169.877539,10.530474,15.814842,3.004609,27.270822,4.383138,14.923626,203.527453,...,154.614465,79.949125,6.518840,7.010760,5.215654,119.869371,84.337063,382.226774,12.088471,5.076376
min,1001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.400000,0.000000,0.000000
25%,9086.250000,29.700000,91.000000,2.380000,0.950000,0.840000,0.050000,0.000000,0.000000,10.000000,...,0.000000,0.200000,0.220000,0.235750,0.220000,0.000000,29.000000,42.000000,0.000000,0.000000
50%,14427.500000,63.080000,191.000000,8.000000,5.140000,1.200000,9.340000,0.700000,1.840000,21.000000,...,0.000000,1.600000,1.592000,1.938500,0.696000,4.000000,85.000000,164.000000,0.000000,10.000000
75%,20142.750000,77.960000,337.000000,19.880000,13.720000,2.090000,34.910000,2.600000,9.287500,69.000000,...,6.000000,5.200000,4.345000,5.115000,2.081000,67.000000,130.000000,305.000000,0.000000,10.000000
max,93600.000000,100.000000,902.000000,88.320000,100.000000,99.800000,100.000000,79.000000,99.800000,7364.000000,...,10000.000000,1714.500000,95.600000,83.689000,74.623000,3100.000000,1184.000000,5717.000000,81.000000,11.000000

In [43]:
df.describe(include='O')

                                                Shrt_Desc
count                                                8790
unique                                               8787
top     BEEF,CHUCK,UNDER BLADE CNTR STEAK,BNLESS,DENVE...
freq                                                    2

In [44]:
import missingno

In [45]:
# # матричная диаграмма пропусков
# missingno.matrix(df, figsize=(10,10), fontsize=12)

In [46]:
# # матричная диаграмма пропусков
# missingno.matrix(df, figsize=(10,10), fontsize=12)

In [47]:
df.fillna(df.mean(), inplace=True)

<ipython-input-47-bf934754a5b1>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean(), inplace=True)

In [48]:
# corr = df.corr()
# corr.style.background_gradient(cmap='RdYlGn')
# corr.style.highlight_max('Protein_(g)')
# corr.style.set_table_styles()

In [49]:
# plt.figure(figsize=(30,30))
# sns.heatmap(df.corr(), linewidths=.0, annot=True)

In [50]:
df.drop(columns=['Vit_D_IU','Vit_A_RAE'], inplace=True)

In [51]:
df.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_µg,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_2,Refuse_Pct,CLASS
0,1001,"BUTTER,WITH SALT",15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,0.0,7.0,51.368,21.021,3.043,215.0,5.00,14.2,0.0,10
1,1002,"BUTTER,WHIPPED,W/ SALT",16.72,718,0.49,78.30,1.62,2.87,0.0,0.06,...,0.0,4.6,45.390,19.874,3.331,225.0,3.80,9.4,0.0,10
2,1003,"BUTTER OIL,ANHYDROUS",0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,0.0,8.6,61.924,28.732,3.694,256.0,12.80,205.0,0.0,0
3,1004,"CHEESE,BLUE",42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,0.5,2.4,18.669,7.778,0.800,75.0,28.35,17.0,0.0,10
4,1005,"CHEESE,BRICK",41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,0.5,2.5,18.764,8.598,0.784,94.0,132.00,113.0,0.0,10

In [52]:
#df.replace(['1 tbsp', '1 cup', '1 cubic inch'],[14.7868, 236.588, 16.3871], inplace=True)

In [53]:
df.head()

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_µg,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_2,Refuse_Pct,CLASS
0,1001,"BUTTER,WITH SALT",15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,0.0,7.0,51.368,21.021,3.043,215.0,5.00,14.2,0.0,10
1,1002,"BUTTER,WHIPPED,W/ SALT",16.72,718,0.49,78.30,1.62,2.87,0.0,0.06,...,0.0,4.6,45.390,19.874,3.331,225.0,3.80,9.4,0.0,10
2,1003,"BUTTER OIL,ANHYDROUS",0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,0.0,8.6,61.924,28.732,3.694,256.0,12.80,205.0,0.0,0
3,1004,"CHEESE,BLUE",42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,0.5,2.4,18.669,7.778,0.800,75.0,28.35,17.0,0.0,10
4,1005,"CHEESE,BRICK",41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,0.5,2.5,18.764,8.598,0.784,94.0,132.00,113.0,0.0,10

In [54]:
#df.GmWt_Desc1.unique()

In [55]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
    df[i]=le.fit_transform(df[i])

In [56]:
df

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_D_µg,Vit_K_(µg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),GmWt_1,GmWt_2,Refuse_Pct,CLASS
0,0,2097,689,642,84,2404,212,6,0,6,...,0,70,3925,3804,1871,187,43,102,0,2
1,1,2096,699,643,49,2393,162,243,0,6,...,0,46,3918,3791,1961,192,33,69,0,2
2,2,2092,15,658,28,2414,0,0,0,0,...,0,86,3931,3885,2047,207,98,320,0,0
3,3,2921,1162,353,1715,2003,475,203,0,50,...,5,24,3760,3028,761,76,132,110,0,2
4,4,2922,1124,371,1876,2033,319,237,0,51,...,5,25,3761,3179,749,95,280,228,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8785,8785,5376,1178,305,1473,1869,648,0,0,0,...,115,78,2965,3130,2376,96,227,110,0,0
8786,8786,7363,2725,111,1642,84,298,455,0,0,...,0,0,210,82,220,42,232,366,0,0
8787,8787,8035,806,269,0,0,86,2849,0,1872,...,0,0,0,0,0,0,121,366,0,2
8788,8788,7584,3343,90,1297,140,130,178,0,0,...,0,1,324,240,249,51,232,366,0,0
8789,8789,8374,3301,89,1575,50,120,0,0,0,...,0,1,126,87,170,51,232,366,0,0

In [57]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [58]:
clf = make_pipeline(KNeighborsClassifier())

In [59]:
x = df.drop(columns='CLASS')
y = df['CLASS']
X_train, X_test, y_train, y_test= train_test_split(x,y , test_size=0.3)

In [60]:
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8763746681835419

In [61]:
clf = make_pipeline(MinMaxScaler(), KNeighborsClassifier())

In [62]:
x = df.drop(columns='CLASS')
y = df['CLASS']
X_train, X_test, y_train, y_test= train_test_split(x,y , test_size=0.3)

In [63]:
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8983693591202123

In [64]:
clf = make_pipeline(StandardScaler(), KNeighborsClassifier())

In [65]:
x = df.drop(columns='CLASS')
y = df['CLASS']
X_train, X_test, y_train, y_test= train_test_split(x,y , test_size=0.3)

In [66]:
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8976109215017065

In [69]:
parameters = {'n_neighbors':[1, 10]}
clf = GridSearchCV(KNeighborsClassifier(), parameters)

In [70]:
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8835798255593478

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
clf = make_pipeline(LogisticRegression())
clf = clf.fit(x, y)
pred = clf.predict(x)
clf.score(x, y)
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
print('Score: %.3f' % clf.score(x,y))
# print('Precision: %.3f' % precision_score(y, pred))
# print('Recall: %.3f' % recall_score(y, pred))
print('Accuracy: %.3f' % accuracy_score(y, pred))
# print('F1 Score: %.3f' % f1_score(y, pred))

Score: 0.861
Accuracy: 0.861

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(